package com.example.pracainzynierska;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.text.Html;
import android.text.method.ScrollingMovementMethod;
import android.widget.TextView;

public class Terms extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_terms);

        TextView textViewTerms;

        textViewTerms = findViewById(R.id.textViewAllTerms);
        textViewTerms.setMovementMethod(new ScrollingMovementMethod());
        textViewTerms.setText(Html.fromHtml("<b><h3>Regulamin aplikacji mobilnej IQTQ obowiązujący od 12 października 2020 roku</h3></b><br> § 1 POSTANOWIENIA WSTĘPNE <br><br>1. Niniejszy Regulamin określa zasady funkcjonowania aplikacji mobilnej IQTQ („Aplikacja”), utworzonej w celu napisania pracy inżynierskiej.<br><br>" +
                "2. W Regulaminie określone są w szczególności rodzaje i zakres usług świadczonych drogą elektroniczną, warunki świadczenia usług drogą elektroniczną w tym wymagania techniczne niezbędne do korzystania z Aplikacji, warunki zawierania i rozwiązywania umów o świadczenie usług drogą elektroniczną oraz tryb postępowania reklamacyjnego, jak również prawa i obowiązki jego Użytkowników, oraz zasady odpowiedzialności Administratora i Użytkowników Aplikacji, zgodnie z ustawą z dnia z dnia 18 lipca 2002 r. o świadczeniu usług drogą elektroniczną (tekst jedn.: Dz. U. 2013 r. poz. 1422).<br><br>" +
                "3. Usługi są świadczone na zasadach określonych w Regulaminie oraz powszechnie obowiązujących przepisów prawa zaś naruszenie przez Użytkownika postanowień Regulaminu powodować będzie skutki wynikające bezpośrednio z treści Regulaminu oraz z w/w przepisów prawa.<br><br>" +
                "4. Treść niniejszego Regulaminu przekazywany jest Użytkownikowi nieodpłatnie przed zarejestrowaniem się do Aplikacji na urządzeniu mobilnym. Brak akceptacji Regulaminu uniemożliwia rejestrację do Aplikacji.<br><br>" +
                "§ 2 DEFINICJE<br><br>Regulamin – oznacza niniejszy regulamin korzystania z aplikacji mobilnej IQTQ.<br><br>Administrator – oznacza studentów IV Roku informatyki Uniwersytetu Kazimierza Wielkiego w Bydgoszczy.<br><br>" +
                "Aplikacja – aplikację – tj. aplikacja mobilna IQTQ, która jest stworzona w celu znalezienia współgraczy do gier sieciowych. Aplikacja jest przygotowana na system operacyjny Android,  w wersji na smartfony i tablety. Aplikacja jest bezpłatna - dostępna dla wszystkich.<br><br>" +
                "Użytkownik – osoba fizyczna, posiadająca pełną zdolność do czynności prawnych.<br><br>Konto - prowadzone dla Użytkownika przez Administratora pod unikalną nazwą (Login, w tym z możliwością logowania za pomocą danych z platformy facebook.com i google.com oraz konta e-mail) konto będące zbiorem zasobów, w którym gromadzone są dane Użytkownika oraz informacje o jego działaniach w ramach Aplikacji, którymi Użytkownik samodzielnie zarządza.<br><br>" +
                "Login - wybrana podczas rejestracji w Aplikacji nazwa Użytkownika, której Użytkownik używać będzie podczas uzyskiwania dostępu do Konta. Istnieje możliwość logowania za pomocą posiadanego przez Użytkownika konta w serwisie Facebook (Facebook.com) lub Google (google.com). W takim przypadku dane z tych serwisów są danymi do logowania w Aplikacji. Login nie może zawierać treści wulgarnych, obraźliwych ani sprzecznych z obowiązującym prawem, nie może również być tożsamy z loginem innego Użytkownika ani naruszać innych zasad określonych w Regulaminie.<br><br>" +
                "Profil – zgromadzony w ramach Konta zbiór informacji, danych i innych elementów prezentujących i opisujących osobę danego Użytkownika, przekazywanych dobrowolnie i samodzielnie przez Użytkownika do Aplikacji, które udostępniane i prezentowane są w Aplikacji.<br><br>Usługi – usługi świadczone przez Administratora na rzecz Użytkownika zgodnie z postanowieniami Regulaminu.<br><br>" +
                "Blokada – blokada, trwała lub czasowa, w zależności od uznania Administratora lub osoby przez niego wyznaczonej, dostępu Użytkownika, który naruszył postanowienia Regulaminu lub przepisów prawa, do Aplikacji, Konta lub poszczególnych elementów Aplikacji; w sytuacjach wskazanych w Regulaminie, przewiduje się także czasowe lub trwałe usunięcie Konta Użytkownika.<br><br>" +
                "§ 3 ZASADY OGÓLNE KORZYSTANIA Z APLIKACJI<br><br>1. Użytkownik może:<br><br>a) zmienić lub usunąć dane Użytkownika w Profilu za pomocą opcji zawartych w Aplikacji;<br><br>b) korzystać z Aplikacji i jego funkcjonalności zgodnie z jego przeznaczeniem oraz zasadami Regulaminu.<br><br>2. Użytkownik jest zobowiązany w szczególności do:<br><br>" +
                "a) powstrzymywania się od jakichkolwiek działań mogących utrudnić lub zakłócić funkcjonowanie Aplikacji oraz od korzystania z Aplikacji i jej funkcjonalności w sposób uciążliwy dla innych Użytkowników lub Administratora;<br><br>b) przestrzegania autorskich praw osobistych oraz majątkowych jak również praw wynikających z rejestracji wynalazków, patentów, znaków towarowych, wzorów użytkowych i przemysłowych innych osób;<br><br>" +
                "c) powstrzymywania się od jakichkolwiek działań naruszających prywatność użytkowników Aplikacji, w szczególności zbierania, przetwarzania i rozpowszechniania informacji o nich bez ich wyraźnej zgody, chyba że jest to dozwolone przez przepisy prawa i postanowienia niniejszego Regulaminu.<br><br>" +
                "3. Niedozwolone jest wykorzystywanie Aplikacji i jej funkcjonalności do celów innych niż wynika to z charakteru i przedmiotu Aplikacji oraz wynikających z niniejszego Regulaminu, w tym celach innych niż korzystanie z Usług, a w szczególności niedozwolone jest:<br><br>a) prowadzenie wszelkiego rodzaju agitacji, w tym politycznej lub religijnej;<br><br>b) rozsyłanie spamu i nie zamówionej informacji handlowej,<br><br>c) podejmowanie jakichkolwiek działań mogących spowodować szkodę, w tym w szczególności szkodę Administratora, innych Użytkowników lub osób trzecich;<br><br>" +
                "d) umieszczanie w Aplikacji nieprawdziwych lub wprowadzających w błąd informacji;<br><br>e) umieszczanie w Aplikacji materiałów naruszających obowiązujące prawo, Regulamin, dobre obyczaje, normy moralne lub zasady uczciwej konkurencji, wulgarnych, obrażających godność, szkalujących lub naruszające dobra osobiste innych osób w tym innych Użytkowników lub Administratora, popierające radykalne postawy społeczne lub głoszące takie poglądy (wszelkiego rodzaju dyskryminacja rasowa, etniczna, ze względu na płeć, wyznanie itp.), treści nieprawdziwych lub wprowadzających w błąd;<br><br>" +
                "f) umieszczanie materiałów erotycznych w jakiejkolwiek formie;<br><br>g) umieszczanie treści niezwiązanych z tematyką lub celem Aplikacji;<br><br>h) sugerowanie w jakikolwiek sposób tożsamości lub związków Użytkownika z Administratorem lub ich działaniem;<br><br>i) podszywanie się pod innych Użytkowników, podawanie lub sugerowanie nieprawdziwej tożsamości Użytkownika.<br><br>5. Użytkownik ponosi pełną odpowiedzialność za korzystanie z Konta i Aplikacji w sposób sprzeczny z Regulaminem lub powszechnie obowiązującym prawem i jego skutki.<br><br>" +
                "6. Za nieprzestrzeganie postanowień Regulaminu lub powszechnie obowiązujących przepisów prawa przez Użytkownika może zostać nałożona na niego Blokada. O nałożeniu blokady decyduje Administrator.<br><br>7. Jeżeli dotycząca części funkcjonalności Aplikacji Blokada nie spowoduje zaprzestania naruszania postanowień Regulaminu lub powszechnie obowiązujących przepisów prawa, dostęp do Aplikacji może zostać trwale zablokowany. W zależności od sytuacji, mogą również zostać usunięte z Aplikacji wszystkie informacje o Użytkowniku.<br><br>" +
                "8. Administrator, w tym działająca w jego imieniu osoba, może usunąć materiały umieszczone w Aplikacji, w jakikolwiek sposób nie spełniające lub naruszające postanowienia Regulaminu lub powszechnie obowiązujących przepisów prawa, bez uprzedzenia lub powiadomienia Użytkownika.<br><br>§ 4 WYMAGANIA TECHNICZNE<br><br>1. Do korzystania z Aplikacji niezbędne jest posiadanie urządzenia mobilnego (w szczególności telefonu komórkowego, tabletu):<br><br>a) umożliwiającego pobieranie i użytkowanie aplikacji mobilnych,<br><br>" +
                "b) umożliwiającego poprawne połączenie się z siecią Internet. Koszty połączenia z Internetem obciążają Użytkownika, stosownie do umów zawartych przez użytkownika z operatorem telekomunikacyjnym.<br><br>c) posiadającego system operacyjny Android 4.4+.<br><br>2. Administrator nie ponosi odpowiedzialności za niedziałanie lub nienależyte działanie Aplikacji na urządzeniu niespełniającym wymagań technicznych określonych w §4 ust 1-2.<br><br>§ 5 REJESTRACJA W RAMACH APLIKACJI<br><br>" +
                "1. Użytkownikiem Aplikacji może być każda osoba fizyczna posiadająca pełną zdolność do czynności prawnych, która zainstalowała Aplikację na urządzeniu mobilnym i zaakceptowała postanowienia Regulaminu oraz podała swoje dane w trakcie procedury rejestracji lub zmiany Użytkownika.<br><br>2. Równoznaczne z rejestracją w ramach Aplikacji jest zalogowanie się do niej za pomocą posiadanego przez Użytkownika konta w serwisie Facebook (Facebook.com), Google (google.com) lub poczty e-mail.<br><br>" +
                "3. Poprzez zrealizowanie procedury rejestracji w Aplikacji, której skutkiem jest założenie Konta, Użytkownik zapewnia i oświadcza, iż zapoznał się i zaakceptował treść całego Regulaminu i zobowiązuje się do jego przestrzegania.<br><br>4. Rejestrując się w Aplikacji Użytkownik wyraża zgodę na publikowanie jego Loginu, E-maila, oraz innych danych uzupełnianych podczas tworzenia konta.<br><br>5. Użytkownik rejestrując się w Aplikacji wyraża ponadto zgodę na:<br><br>" +
                "a) zbieranie przez Administratora danych osobowych Użytkownika pozyskanych w trakcie rejestracji i ich przetwarzanie w zakresie wskazanym w § 9 Regulaminu.<br><br>6. Użytkownik zobowiązany jest do podawania, zarówno w procesie rejestracji jak i w każdym czasie korzystania z Aplikacji, informacji prawdziwych i rzetelnych. Ujawnienie nieprawidłowości wszystkich lub niektórych danych podanych przez Użytkownika może skutkować Blokadą.<br><br>" +
                "7. Założenie Konta wymaga od Użytkownika podania Loginu, adresu e-mail oraz hasła, z którego będzie korzystał używając Aplikacji.<br><br>8. Informacje przekazywane przez Użytkownika do Aplikacji podczas procedury rejestracji, edycji Profilu lub korzystania z Aplikacji, mogą być moderowane przez Administratora, w tym Administrator może odmówić opublikowania ich w ramach Aplikacji.<br><br>" +
                "9. Użytkownik może w każdej chwili usunąć swoje Konto z Aplikacji oraz odinstalować Aplikację z urządzenia mobilnego, a deinstalacja Aplikacji jest równoznaczna z usunięciem Konta Użytkownika i rozwiązaniu umowy o świadczenie usług drogą elektroniczną, jednak nie wyklucza to ponownej rejestracji po ponownym zainstalowaniu Aplikacji Wraz z usunięciem Konta usunięty zostanie z Aplikacji Profil Użytkownika na stałe i bezpowrotnie. Po usunięciu Konta nie ma możliwości jego przywrócenia, natomiast istnieje możliwość ponownego założenia Konta przez tego samego Użytkownika.<br><br>" +
                "§ 6 KONTO UŻYTKOWNIKA<br><br>1. Posiadanie przez Użytkownika Konta w ramach Aplikacji, jak również przeglądanie i zmiana danych, dodawanie dozwolonych Regulaminem materiałów jest bezpłatne.<br><br>2. Konta nie używane (brak skutecznego logowania) przez okres dłuższy niż 12 miesięcy od ostatniego logowania, mogą zostać usunięte bez uprzedniego powiadomienia.<br><br>3. W przypadku stwierdzenia naruszenia przez Użytkownika zasad Regulaminu lub powszechnie obowiązujących przepisów prawa, Konto może zostać zablokowane (na stałe lub tymczasowo) bądź usunięte bez konieczności podania przyczyny i informowania o tym fakcie.<br><br>" +
                "4. Każde nowo założone Konto jest Kontem aktywnym po ukończeniu procesu rejestracji opisanego w Regulaminie.<br><br>5. Administrator będzie domniemywał, że informacje i oświadczenia wysłane z adresu poczty elektronicznej podanej przez Użytkownika pochodzą od Użytkownika, oraz że czynności dokonane przez osobę zalogowaną do Aplikacji z pomocą Loginu i hasła Użytkownika, zostały dokonane przez Użytkownika, chyba że Użytkownik przedstawi dowód przeciwny.<br><br>6. Wszelkie informacje umieszczane w Aplikacji muszą być prawdziwe, rzetelne i nie mogą wprowadzać w błąd.<br><br>" +
                "7. Informacje i inne materiały umieszczane w Aplikacji nie mogą naruszać postanowień Regulaminu.<br><br>8. Administrator nie udostępni Loginu osobom trzecim, o ile nie będzie wymagał tego odpowiedni przepis prawa.<br><br>§ 7 ZGŁASZANIE BŁĘDÓW W DZIAŁANIU APLIKACJI<br><br>1. Błędy dotyczące nienależytego działania Aplikacji należy zgłaszać na adres e-mail: Mat.Tom.PracaInz@gmail.com.<br><br>2. Zgłoszenie powinno zawierać:<br><br>a) określenie podmiotu dokonującego reklamacji (login Użytkownika)<br><br>b) określenie problemu oraz krótki opis.<br><br>" +
                "3. Zgłoszony problem zostanie rozpatrzony najszybciej jak to jest możliwe po otrzymaniu wiadomości przez Administratora.<br><br>4. Administrator dołoży wszelkich starań, aby Aplikacja oraz wszystkie Usługi udostępniane za jej pośrednictwem działały w sposób ciągły i bez zakłóceń, jednakże Administrator nie ponosi odpowiedzialności za zakłócenia spowodowane działaniem siły wyższej, awariami lub niedozwoloną ingerencją Użytkowników lub osób trzecich, niewystarczającą przepustowością łącza za pomocą którego Użytkownik korzysta z Aplikacji, naruszeniem warunków Regulaminu przez Użytkownika.<br><br>" +
                "5. Administrator zastrzega sobie prawo do czasowego całkowitego lub częściowego wyłączenia Aplikacji w celu jej ulepszenia, dodawania usług lub przeprowadzania konserwacji, bez wcześniejszego uprzedzania o tym Użytkowników.<br><br>6. Administrator zastrzega sobie możliwość wdrażania do Aplikacji we wszelkich jej płaszczyznach, rozwiązań funkcjonalnych, identyfikacyjnych lub innych, które okażą się odpowiednie do przedmiotu lub uwarunkowań technicznych Aplikacji, w związku z możliwościami występowania zachowań lub zdarzeń niepożądanych bądź zagrażających prawom lub interesom Użytkowników, Administratora albo uzasadnionym interesom osób trzecich.<br><br>" +
                "§ 9 DANE OSOBOWE<br><br>1. Szczegółowe zasady przetwarzania danych w ramach Aplikacji określa POLITYKA PRYWATNOŚCI APLIKACJI IQTQ, na której treść  Użytkownik akceptując niniejszy Regulamin wyraża swoją zgodę.<br><br>2. Administratorami danych osobowych udostępnionych przez Użytkownika są studenci Uniwersytetu Kazimierza Wielkiego w Bydgoszczy.<br><br>" +
                "3. Dokonując rejestracji w Aplikacji, Użytkownik może wyrazić zgodę na przesyłanie przez Administratora informacji handlowej zgodnie z przepisami ustawy z dnia 18 lipca 2002r. o świadczeniu usług drogą elektroniczną, na adres poczty elektronicznej podany przez Użytkownika, dotyczącej Aplikacji, działalności Administratora, jego podmiotów dominujących, zależnych lub powiązanych, jak również jego partnerów handlowych.<br><br>§ 10 POSTANOWIENIA KOŃCOWE<br><br>" +
                "1. Wszelkie postanowienia Regulaminu mogą być w każdej chwili zmieniane przez Administratora. Każda zmiana Regulaminu zostanie Użytkownikowi zakomunikowana poprzez Aplikacje wraz z informacją o jej dokonaniu.<br><br>2. Regulamin wchodzi w życie w terminie 14 dni od jego opublikowania w Aplikacji<br><br>3. Po ukazaniu się w Aplikacji informacji o zmianach w Regulaminie, Użytkownik powinien niezwłocznie zapoznać się ze zmianami, gdyż zalogowanie na Konto po wejściu Regulaminu w życie stanowi akceptację nowej treści Regulaminu przez Użytkownika.<br><br>" +
                "4. W przypadku nie zaakceptowania zmian w Regulaminie, Użytkownik powinien powstrzymać się od zalogowania na Konto i niezwłocznie powiadomić Administratora o takiej decyzji w formie mailowej na adres Mat.Tom.PracaInz@gmail.com<br><br>5. Oświadczenie o nie zaakceptowaniu zmian w Regulaminie, pociąga za sobą usunięcie Konta Użytkownika.<br><br>6. Niniejszy Regulamin wchodzi w życie z dniem ogłoszenia i wiąże w tej wersji do dnia jego zmiany lub odwołania."));
        textViewTerms.setTextSize(16);
    }
}